export const SET_MOVING_PAWN = 'SET_MOVING_PAWN';
export const SET_PAWN_PLACE = 'SET_PAWN_PLACE';
export const SET_DICE = 'SET_DICE';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_MOVEMENTS = 'SET_MOVEMENTS';
export const SET_ACTION = 'SET_ACTION';
export const SET_CURRENT_GAME_STEP = 'SET_CURRENT_GAME_STEP';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_ACTIVE_PLAYERS = 'SET_ACTIVE_PLAYERS';

export const MUTATIONS = {
    SET_MOVING_PAWN,
    SET_PAWN_PLACE,
    SET_DICE,
    SET_CURRENT_PLAYER,
    SET_MOVEMENTS,
    SET_ACTION,
    SET_CURRENT_GAME_STEP,
    SET_PLAYER_NAME,
    SET_ACTIVE_PLAYERS,
};
